site_name: "http-foxes"
publish_dir: "publish"
picture_dir: "pictures"
font_file: "fonts/NotoSerif-Regular.ttf"
link_prefix: "https://f.cus.moe"
test_server_port: 14000
pictures:
  - s: "100 Continue"
    d: "This interim response indicates that everything so far is OK and that the client should continue the request, or ignore the response if the request is already finished."
    a: "Ray Hennessy"
    u: "https://unsplash.com/photos/R6ZlnE1zdS4"
  - s: "101 Switching Protocol"
    d: "This code is sent in response to an Upgrade request header from the client, and indicates the protocol the server is switching to."
    a: "Ray Hennessy"
    u: "https://unsplash.com/photos/9rloii_qmmw"
  - s: "102 Processing (WebDAV)"
    d: "This code indicates that the server has received and is processing the request, but no response is available yet."
    a: "Nathan Anderson"
    u: "https://unsplash.com/photos/7TGVEgcTKlY"
  - s: "206 Partial Content"
    d: "This response code is used when the Range header is sent from the client to request only part of a resource."
    a: "Sora Sagano"
    u: "https://unsplash.com/photos/NjSa_0q3Hkg"
  - s: "302 Found"
    d: "This response code means that the URI of requested resource has been changed temporarily. Further changes in the URI might be made in the future. Therefore, this same URI should be used by the client in future requests."
    a: "Jonatan Pie"
    u: "https://unsplash.com/photos/USdG7McCLeA"
  - s: "401 Unauthorized"
    d: "Although the HTTP standard specifies \"unauthorized\", semantically this response means \"unauthenticated\". That is, the client must authenticate itself to get the requested response."
    a: "Janet Wiedenhoeft"
    u: "https://unsplash.com/photos/F1-26P2KbaA"
  - s: "403 Forbidden"
    d: "The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401, the client's identity is known to the server."
    a: "Peter Lloyd"
    u: "https://unsplash.com/photos/N2Ze4fdnums"
  - s: "404 Not Found"
    d: "The server can not find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 to hide the existence of a resource from an unauthorized client. This response code is probably the most famous one due to its frequent occurrence on the web."
    a: "Photoholgic"
    u: "https://unsplash.com/photos/DU_NpuvUAxY"
  - s: "409 Conflict"
    d: "This response is sent when a request conflicts with the current state of the server."
    a: "cloudvisual"
    u: "https://unsplash.com/photos/DCtwjzQ9uVE"
  - s: "418 I'm a teapot"
    d: "The server refuses the attempt to brew coffee with a teapot."
    a: "Liam Read"
    u: "https://unsplash.com/photos/ZfvMAof3ERQ"
  - s: "425 Too Early"
    d: "Indicates that the server is unwilling to risk processing a request that might be replayed."
    a: "fatty corgi"
    u: "https://unsplash.com/photos/EpRAM95thHU"
  - s: "426 Upgrade Required"
    d: "The server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol. The server sends an Upgrade header in a 426 response to indicate the required protocol(s)."
    a: "Judith Prins"
    u: "https://unsplash.com/photos/AfQVC7KSWfM"
  - s: "431 Request Header Fields Too Large"
    d: "The server is unwilling to process the request because its header fields are too large. The request may be resubmitted after reducing the size of the request header fields."
    a: "Peter Lloyd"
    u: "https://unsplash.com/photos/H6U_0nC-Sbk"
